### PR TITLE
Avoid changing global config

### PR DESCRIPTION
**Pull request by anki-code**
Hey!
Instead of changing global config (it's bad pattern) I suggest to wrap your changes into the context manager.

### CODE REVIEW

**Comment by anki-code** [comment]
@74th please take a look.

**Comment by con-f-use** [comment]
We want the changes to persist for the entire shell session. Wouldn't the context manager undo them at the end of the function?

Edit: Nevermind, it just undoes the `$UPDATE_OS_ENVIRON=True`.

**Review by con-f-use — APPROVED** [review]

**Comment by con-f-use** [comment]
@anki-code Thanks for finding and PR-ing. Please bump the [patch version](https://github.com/74th/xonsh-direnv/blob/master/setup.py#L8) and add a release note to README.md

**Comment by anki-code** [comment]
Thank you for review @con-f-use ! 

> Please bump the [patch version](https://github.com/74th/xonsh-direnv/blob/master/setup.py#L8) and add a release note to README.md

Done.

> Edit: Nevermind, it just undoes the $UPDATE_OS_ENVIRON=True.

It returns UPDATE_OS_ENVIRON to the previous state. It's the right pattern.

**Review by 74th — APPROVED** [review]
Thank you for PR!
I will release this patch now.

**Pull request merged**
